### ISSUE TITLE
Trying to compile gives error Makefile:77: recipe for target 'page_file.o' failed make: *** [page_file.o] Error 1

### ISSUE THREAD

**Issue by stevethearkiv** [PRHLT/pageDistanceBasedContourGenerator#7] opened 2020-05-28 11:17 UTC
Cant seem to get past

Makefile:77: recipe for target 'page_file.o' failed
make: *** [page_file.o] Error 1

**Comment by vbosch** [comment] 2020-06-04 23:16
Dear stevethearkiv,
I tested the code in a clean docker machine with all the required software installed "vbosch/uobel" and I downloaded and compiled the code without a problem: 
`sudo docker run --rm -it --name uobel vbosch/uobel bash
root@4cd3947d4fd6:/home# git clone https://github.com/PRHLT/pageDistanceBasedContourGenerator.git
Cloning into 'pageDistanceBasedContourGenerator'...
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 157 (delta 2), reused 4 (delta 2), pack-reused 149
Receiving objects: 100% (157/157), 2.26 MiB | 2.57 MiB/s, done.
Resolving deltas: 100% (69/69), done.
Checking connectivity... done.

root@4cd3947d4fd6:/home# cd pageDistanceBasedContourGenerator/
root@4cd3947d4fd6:/home/pageDistanceBasedContourGenerator# 
root@4cd3947d4fd6:/home/pageDistanceBasedContourGenerator# ls
156730303.jpg                        algorithm_dbosch.hpp           algorithm_extract_polygons.hpp  algorithm_sauvola.hpp     line_histogram.cc     polyline_extractor.cc
156730303.xml                        algorithm_distance_map.cc      algorithm_kmeans.cc             algorithm_wdtocs.cc       line_histogram.hpp    polyline_extractor.hpp
LICENSE                              algorithm_distance_map.hpp     algorithm_kmeans.hpp            algorithm_wdtocs.hpp      line_region_list.cc   pugiconfig.hpp
Makefile                             algorithm_dp_path_finder.cc    algorithm_otsu.cc               extract_lines_v3.cc       line_region_list.hpp  pugixml.cpp
README.md                            algorithm_dp_path_finder.hpp   algorithm_otsu.hpp              grey_level_histogram.cc   page_file.cc          pugixml.hpp
algorithm_calculate_search_area.cc   algorithm_dtocs.cc             algorithm_rlsa.cc               grey_level_histogram.hpp  page_file.hpp
algorithm_calculate_search_area.hpp  algorithm_dtocs.hpp            algorithm_rlsa.hpp              image.cc                  points_file.cc
algorithm_dbosch.cc                  algorithm_extract_polygons.cc  algorithm_sauvola.cc            image.hpp                 points_file.hpp
root@4cd3947d4fd6:/home/pageDistanceBasedContourGenerator# make all
g++ -c -O3 -o extract_lines_v3.o extract_lines_v3.cc `pkg-config --cflags-only-I opencv liblog4cxx eigen3` -I./ -I/opt/local/include/
g++ -w -c -O3 -pthread -o page_file.o page_file.cc `pkg-config --cflags-only-I opencv liblog4cxx eigen3` -I./ -I/opt/local/include/
g++ -w -c -O3 -pthread -o algorithm_calculate_search_area.o algorithm_calculate_search_area.cc `pkg-config --cflags-only-I opencv liblog4cxx eigen3` -I./ -I/opt/local/include/
g++ -w -c -O3 -pthread -o algorithm_extract_polygons.o algorithm_extract_polygons.cc `pkg-config --cflags-only-I opencv liblog4cxx eigen3` -I./ -I/opt/local/include/
g++ -w -c -O3 -pthread -o pugixml.o pugixml.cpp `pkg-config --cflags-only-I opencv liblog4cxx eigen3` -I./ -I/opt/local/include/
g++    -c -o points_file.o points_file.cc
g++ -w -c -O3 -pthread -o algorithm_distance_map.o algorithm_distance_map.cc `pkg-config --cflags-only-I opencv liblog4cxx eigen3` -I./ -I/opt/local/include/
g++ -w -c -O3 -pthread -o algorithm_wdtocs.o algorithm_wdtocs.cc `pkg-config --cflags-only-I opencv liblog4cxx eigen3` -I./ -I/opt/local/include/
g++ -w -c -O3 -pthread -o algorithm_dtocs.o algorithm_dtocs.cc `pkg-config --cflags-only-I opencv liblog4cxx eigen3` -I./ -I/opt/local/include/
g++ -w -c -O3 -pthread -o image.o image.cc `pkg-config --cflags-only-I opencv liblog4cxx eigen3` -I./ -I/opt/local/include/
g++ -w -c -O3 -pthread -o algorithm_otsu.o algorithm_otsu.cc `pkg-config --cflags-only-I opencv liblog4cxx eigen3` -I./ -I/opt/local/include/
g++ -w -c -O3 -pthread -o grey_level_histogram.o grey_level_histogram.cc `pkg-config --cflags-only-I opencv liblog4cxx eigen3` -I./ -I/opt/local/include/
g++ -w -c -O3 -pthread -o line_histogram.o line_histogram.cc `pkg-config --cflags-only-I opencv liblog4cxx eigen3` -I./ -I/opt/local/include/
g++ -w -c -O3 -pthread -o algorithm_kmeans.o algorithm_kmeans.cc `pkg-config --cflags-only-I opencv liblog4cxx eigen3` -I./ -I/opt/local/include/
g++ -w -c -O3 -pthread -o algorithm_sauvola.o algorithm_sauvola.cc `pkg-config --cflags-only-I opencv liblog4cxx eigen3` -I./ -I/opt/local/include/
g++ -w -c -O3 -pthread -o algorithm_dp_path_finder.o algorithm_dp_path_finder.cc `pkg-config --cflags-only-I opencv liblog4cxx eigen3` -I./ -I/opt/local/include/
g++ -w -c -O3 -pthread -o line_region_list.o line_region_list.cc `pkg-config --cflags-only-I opencv liblog4cxx eigen3` -I./ -I/opt/local/include/
g++ -w -c -O3 -pthread -o algorithm_dbosch.o algorithm_dbosch.cc `pkg-config --cflags-only-I opencv liblog4cxx eigen3` -I./ -I/opt/local/include/
g++    -c -o algorithm_rlsa.o algorithm_rlsa.cc
g++ -w -c -O3 -pthread -o polyline_extractor.o polyline_extractor.cc `pkg-config --cflags-only-I opencv liblog4cxx eigen3` -I./ -I/opt/local/include/
g++  -m64 -O3 -o extract_lines extract_lines_v3.o page_file.o algorithm_calculate_search_area.o algorithm_extract_polygons.o pugixml.o points_file.o algorithm_distance_map.o algorithm_wdtocs.o algorithm_dtocs.o image.o algorithm_otsu.o grey_level_histogram.o line_histogram.o algorithm_kmeans.o algorithm_sauvola.o algorithm_dp_path_finder.o line_region_list.o algorithm_dbosch.o algorithm_rlsa.o polyline_extractor.o  `pkg-config --cflags-only-I opencv liblog4cxx eigen3` -I./ -I/opt/local/include/ `pkg-config liblog4cxx opencv eigen3 --libs` -lboost_system -lboost_program_options -lboost_filesystem     -lboost_thread -lboost_regex
root@4cd3947d4fd6:/home/pageDistanceBasedContourGenerator# 
`
Thus there does not seem to be any issues with the current state of the repository. Please provide additional information regarding your issue so that I may help you out. Otherwise I will have to close this issue due to it not being reproducible for me. 

Best,
Vicent

**Comment by vbosch** [comment] 2020-06-18 07:22
Clossing issue due to no further information being provided in 2 weeks. 

Regards,
V.

**Closed as completed by vbosch** 2020-06-18 07:22 UTC

**Comment by stevethearkiv** [comment] 2020-08-24 19:56
I think the problem is I am using all newer libraries

**Comment by stevethearkiv** [comment] 2020-08-24 19:58
libopencv-dev                                     3.2.0+dfsg-4ubuntu0.1
libboost1.65-dev:amd64                    1.65.1+dfsg-0ubuntu5
libeigen3-dev                                     3.3.4-4 
liblog4cxx-dev:amd64                              0.10.0-13ubuntu2
